### ISSUE TITLE
Birthday CalDav Sync

### ISSUE THREAD

**Issue by Op3rat0r** [libasys/tasksplus#10]
Hi,

first thanks for the nice App. I was searching for a solution to sync my Calendar and Contacts with Android and Outlook. You guys made it achievable.

So now I use all '+' App's. In the Browser (atm Firefox, for testing purposes) the Birthday sync with Calendar+ works great. But there is now way to sync the birthdays to the Android or Outlook calendar.

regards
Daniel from Germany

**Comment by libasys** [comment]
wrong repo! But syncing birthdays should now work!
