### ISSUE TITLE
moved Taskplus to app folder and got blank page

### ISSUE THREAD

**Issue by ShinyShrimp** [libasys/tasksplus#12]
I got this issue:
"I just tried to use Tasksplus and after i moved it to app folder and refresh my owncloud, i just have a white page. I get my owncloud back by removing Tasksplus."

my tasksapp is removed.

what can I do?

**Comment by libasys** [comment]
Do you have calendar+ installed, also? This app only works if calendar+ is installed!

**Comment by ShinyShrimp** [comment]
oh yes that solved it! :) thanks!
