### ISSUE TITLE
Counting Tasks

### ISSUE THREAD

**Issue by mitpro** [libasys/tasksplus#13]
English Version:
In the overview of all lists the number of tasks are alway all tasks in the list - included the done ones.

Wount it be besser, if it would be shows the undone tasks?

German Version:
In der Übersicht aller Aufgabenlisten, wird die Anzahl der Aufgaben in der Liste angezeigt.
Meiner Meinung nach wäre es Sinnvoller nur die noch offnen Aufgaben zu zählen, da die abgeschlossenen Aufgaben ja in der Regel nicht mehr relevant sind.

**Comment by libasys** [comment]
added on all tasks new counter view! done / open! thanks for the hint!
