### ISSUE TITLE
Calendar icon disappears from task after it's been opened and saved

### ISSUE THREAD

**Issue by Visual-Notes** [libasys/tasksplus#14]
This is just a small inconsistency, maybe even intentionally, but i see no reason behind it: 

in the tasks list of a selected calendar only those tasks do show the icon of the related calendar, that have not been opened/modified. As soon as a newly created task is opened and saved again, the icon of the calendar next to the task's name has disappeared.
Shouldn't the icons all be visible any time?

![task_icons](https://cloud.githubusercontent.com/assets/1451511/9603201/6efb93de-50af-11e5-9a80-a9272d19127f.jpg)

**Comment by libasys** [comment]
gui design changed so the problem not more exist! thanks for your bug reporting!
