### ISSUE TITLE
Add new entry only visible after selecting a calendar

### ISSUE THREAD

**Issue by Bullnados** [libasys/tasksplus#6]
First time u load Task+ App there is no button shown. After you seleced a calendar you can add a new entry and than the button is vissible until reload
I think it is would be better, than the add new entry button is visible all the time.

**Comment by diraol** [comment]
The "problem" seems to be on Line 1600 of app.js (
https://github.com/libasys/tasksplus/blob/5bed55fcd2face5051ec5b658e602a8bcba1efa5/js/app.js#L1600 )

```
$(document).ready(function() {
  $('#newTodoButton').hide();
```

Maybe just commenting/removing that line would fix this issue.

**Comment by libasys** [comment]
This is needed for permission control if a calendar is shared and the  user have not create a new task!, but i look deeper for a smarter solution!

**Comment by diraol** [comment]
@libasys on the default view of Task+ all tasks, from all calendars, are shown right? This kind of control (permission to create a new task) could be inside the "new task" form, just allowing the user to create the task on calendars where he have permission.

Does this logic works for you? If so, I can try to help you moving this logic control from "new todo" button to the new todo form calendar selector.

**Comment by 1337sup3rh4x0r** [comment]
For me too, this is one click to much :)

**Comment by libasys** [comment]
new gui design, behaviour changed!
