### ISSUE TITLE
no list refresh after deleting task

### ISSUE THREAD

**Issue by abyssox** [libasys/tasksplus#7]
Expected behaviour: 
Open a task, hit the "delete" botton, confirm with "Yes". The task entry should get removed from the list.

Current behaviour: 
Open a task, hit the "delete" botton, confirm with "Yes". The task gets removed in background but the popup is still shown and the task is still shown in the list. Only after refreshing the page the task gets removed from the list.

Tested with latest FF and Chrome, OC 8.1.0 and Tasksplus 1.0.1

**Comment by Visual-Notes** [comment]
Two other points, that i want to add:

1) At least on Mac with Firefox, the confirmation dialog window opens behind the task properties window, only the "Yes" button of it is partly visible. The dialog box should open in front of the properties window.

2) After confirming by clicking on "Yes", both windows should close automatically. Currently the task properties window stays open and has to be closed manually by clicking on "Discard".

**Comment by libasys** [comment]
fixed in current version
